services:
  app_1:
    build: ./app/.
    container_name: nombre_app_1
    networks:
      - red_1
    environment:
      - DB_HOST=nombre_bbdd_1 # aquí ponemos el nombre del contenedor de bbdd
    ports:
      - "1234:3000"
    depends_on:
      - bbdd_1 # tenemos que poner el nombre del servicio
    
  bbdd_1:
    build: ./bbdd/.
    container_name: nombre_bbdd_1
    networks:
      - red_1
    volumes:
      - datos_postgres:/var/lib/postgresql/data

  app_2:
    build: ./app/.
    container_name: nombre_app_2
    networks:
      - red_2
    environment:
      - DB_HOST=nombre_bbdd_2 # aquí ponemos el nombre del contenedor
    ports:
      - "1235:3000"
    depends_on:
      - bbdd_2 # tenemos que poner el nombre del servicio

  bbdd_2:
    build: ./bbdd/.
    container_name: nombre_bbdd_2
    networks:
      - red_2
    volumes:
      - datos_postgres:/var/lib/postgresql/data
  
networks:
  red_1:
    driver: bridge

  red_2:
    driver: bridge

volumes:
  datos_postgres:
    driver: local